// web_ts/appjona_angular/src/app/views/uiiniciarsesion/ui-iniciar-sesion-impl.component.ts
// ui-iniciar-sesion-impl.component.ts
// Capa: Implementation — solo métodos, sin HTML
// Responsabilidad: sobreescribir login, goToCreateAccount, goToRecoverPassword con lógica real
// Restricciones: sin template propio — reutiliza el templateUrl del Template
import { Component, OnInit } from '@angular/core';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { UiIniciarSesionComponent } from './ui-iniciar-sesion.component';

@Component({
  selector: 'app-ui-iniciar-sesion-impl',
  standalone: true,
  imports: [FormsModule],
  // Reutiliza el template del componente base — sin duplicar HTML
  templateUrl: './ui-iniciar-sesion.component.html',
})
export class UiIniciarSesionImplComponent extends UiIniciarSesionComponent implements OnInit {
  private authService = inject(AuthService);
  private router = inject(Router);

  override ngOnInit(): void {
    console.log('UiIniciarSesionImpl mounted (implementation)');
  }

  override login(email: string, password: string): void {
    this.authService.login(email, password)
      .then(response => {
        localStorage.setItem('jona_authenticated', 'true');
        localStorage.setItem('jona_token', response.token);
        localStorage.setItem('jona_user', JSON.stringify(response.user));
        this.router.navigate(['/homesesion']);
      })
      .catch(error => {
        console.error('Login failed:', error);
        window.alert(error.message);
      });
  }

  override goToCreateAccount(): void {
    window.alert('Implementation — go to create account');
  }

  override goToRecoverPassword(): void {
    window.alert('Implementation — go to recover password');
  }
}

// web_ts/app_jona_systemdesign_react_hooks/src/views/uiiniciarsesion/UiIniciarSesionImpl.ts
// UiIniciarSesionImpl.ts — Level 3: Organism / JONA Layer: Implementation
// Integrator's responsibility. Methods only — no UI code.
// Overrides Template methods with real service calls.
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useUiIniciarSesion } from './UiIniciarSesion';
import { AuthService } from '../../services/AuthService';

export function useUiIniciarSesionImpl() {
  const base = useUiIniciarSesion();
  const navigate = useNavigate();

  function login(email: string, password: string): void {
    AuthService.login(email, password)
      .then((res) => {
        localStorage.setItem('jona_authenticated', 'true');
        localStorage.setItem('jona_token', res.token);
        localStorage.setItem('jona_user', JSON.stringify(res.user));
        navigate('/homesesion');
      })
      .catch((err: { message: string }) => {
        window.alert(err.message ?? 'Login failed');
      });
  }

  function goToCreateAccount(): void {
    window.alert('Navigate to create account');
  }

  function goToRecoverPassword(): void {
    window.alert('Navigate to recover password');
  }

  function handlerLogin(e: React.FormEvent): void {
    e.preventDefault();
    if (base.isValidData(base.email, base.password)) {
      login(base.email, base.password);
    }
  }

  return {
    ...base,
    login,
    goToCreateAccount,
    goToRecoverPassword,
    handlerLogin,
    handlerGoToCreateAccount: goToCreateAccount,
    handlerGoToRecoverPassword: goToRecoverPassword,
  };
}
