// web_ts/appjona_react_hooks/src/views/uiiniciarsesion/UiIniciarSesionImpl.tsx
// UiIniciarSesionImpl.tsx
// Implementation hook — integrator's responsibility
// Methods only, no UI code
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useUiIniciarSesion } from './UiIniciarSesion';
import { AuthService } from '../../services/AuthService';
import React from 'react';

export function useUiIniciarSesionImpl() {
  const base = useUiIniciarSesion();
  const navigate = useNavigate();

  useEffect(() => {
    console.log('useUiIniciarSesionImpl mounted (implementation)');
  }, []);

  // Override login — calls AuthService (mock)
  function login(email: string, password: string): void {
    AuthService.login(email, password)
      .then((response) => {
        console.log('Login successful:', response);
        // Save token and user data to localStorage
        localStorage.setItem('jona_authenticated', 'true');
        localStorage.setItem('jona_token', response.token);
        localStorage.setItem('jona_user', JSON.stringify(response.user));
        // Navigate to session view
        navigate('/homesesion');
      })
      .catch((error) => {
        console.error('Login failed:', error);
        window.alert(error.message);
      });
  }

  // Override goToCreateAccount
  function goToCreateAccount(): void {
    window.alert('Go to create account');
    console.log('Implementation — navigating to create account');
  }

  // Override goToRecoverPassword
  function goToRecoverPassword(): void {
    window.alert('Go to recover password');
    console.log('Implementation — navigating to recover password');
  }

  function isValidData(email: string, password: string): boolean {
    return email !== '' && password !== '';
  }

  function handlerLogin(e: React.FormEvent): void {
    e.preventDefault();
    if (isValidData(base.email, base.password)) {
      login(base.email, base.password);
    } else {
      window.alert('Please fill in both fields.');
    }
  }

  function handlerGoToCreateAccount(): void {
    goToCreateAccount();
  }

  function handlerGoToRecoverPassword(): void {
    goToRecoverPassword();
  }

  return {
    ...base,
    login,
    goToCreateAccount,
    goToRecoverPassword,
    isValidData,
    handlerLogin,
    handlerGoToCreateAccount,
    handlerGoToRecoverPassword,
  };
}

// web_ts/appjona_angular/src/app/views/uiiniciarsesion/ui-iniciar-sesion-impl.component.ts
// ui-iniciar-sesion-impl.component.ts
// Capa: Implementation — solo métodos, sin HTML
// Responsabilidad: sobreescribir login, goToCreateAccount, goToRecoverPassword con lógica real
// Restricciones: sin template propio — reutiliza el templateUrl del Template
import { Component, OnInit } from '@angular/core';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { UiIniciarSesionComponent } from './ui-iniciar-sesion.component';

@Component({
  selector: 'app-ui-iniciar-sesion-impl',
  standalone: true,
  imports: [FormsModule],
  // Reutiliza el template del componente base — sin duplicar HTML
  templateUrl: './ui-iniciar-sesion.component.html',
})
export class UiIniciarSesionImplComponent extends UiIniciarSesionComponent implements OnInit {
  private authService = inject(AuthService);
  private router = inject(Router);

  override ngOnInit(): void {
    console.log('UiIniciarSesionImpl mounted (implementation)');
  }

  override login(email: string, password: string): void {
    this.authService.login(email, password)
      .then(response => {
        localStorage.setItem('jona_authenticated', 'true');
        localStorage.setItem('jona_token', response.token);
        localStorage.setItem('jona_user', JSON.stringify(response.user));
        this.router.navigate(['/homesesion']);
      })
      .catch(error => {
        console.error('Login failed:', error);
        window.alert(error.message);
      });
  }

  override goToCreateAccount(): void {
    window.alert('Implementation — go to create account');
  }

  override goToRecoverPassword(): void {
    window.alert('Implementation — go to recover password');
  }
}
