// web_ts/appjona_vuejs/src/views/uihome/UiHomeView.vue
<!-- UiHomeView.vue -->
<!-- Capa: View Orchestrator — instancia el Impl e inyecta en el Template -->
<!-- Registrado en el router en la ruta /login -->
<template>
  <UiHome v-bind="impl" />
</template>

<script setup lang="ts">
import { useUiHomeImpl } from './use-ui-home-impl'
import UiHome from './UiHome.vue'

const impl = useUiHomeImpl()
</script>

// react_ts/appjona_react_hooks/src/views/uihome/UiHomeView.tsx
// UiHomeView.tsx
// Orquesta: instancia el hook impl e inyecta en el componente visual
import React from 'react';
import { UiHome } from './UiHome';
import { useUiHomeImpl } from './UiHomeImpl';

export const UiHomeView: React.FC = () => {
  const impl = useUiHomeImpl();

  return <UiHome {...impl} />;
};
