// web_ts/appjona_angular/src/app/views/uihome/ui-home.component.ts
// ui-home.component.ts
// Capa: Template — estructura visual de la vista Home
// Responsabilidad: layout con BorderLayout + Header + Footer + formulario de login
// Restricciones: nunca importar servicios externos, navegación ni storage
import { Component, OnInit } from '@angular/core';
import { BorderLayoutComponent } from '../../uilayouts/border-layout.component';
import { HeaderComponent } from '../../uiutils/header.component';
import { FooterComponent } from '../../uiutils/footer.component';
import { UiIniciarSesionComponent } from '../uiiniciarsesion/ui-iniciar-sesion.component';
import { InterUiHome } from './inter-ui-home';

@Component({
  selector: 'app-ui-home',
  standalone: true,
  imports: [BorderLayoutComponent, HeaderComponent, FooterComponent, UiIniciarSesionComponent],
  template: `
    <app-border-layout>
      <app-header slot="north" />
      <app-ui-iniciar-sesion slot="center" />
      <app-footer slot="south" />
    </app-border-layout>
  `,
})
export class UiHomeComponent implements InterUiHome, OnInit {
  ngOnInit(): void {
    this.onMount();
  }

  onMount(): void {
    console.log('UiHome mounted (template)');
  }
}

// web_ts/appjona_vuejs/src/views/uihome/UiHome.vue
<!-- UiHome.vue -->
<!-- Capa: Template — layout visual de la vista Home -->
<!-- Restricciones: sin servicios externos, sin navegación, sin storage -->
<template>
  <BorderLayout>
    <template #north><Header /></template>
    <template #center>
      <UiIniciarSesion
        :email="email"
        :password="password"
        :handler-login="handlerLogin"
        :handler-go-to-create-account="handlerGoToCreateAccount"
        :handler-go-to-recover-password="handlerGoToRecoverPassword"
      />
    </template>
    <template #south><Footer /></template>
  </BorderLayout>
</template>

<script setup lang="ts">
import type { Ref } from 'vue'
import BorderLayout from '../../uilayouts/BorderLayout.vue'
import Header from '../../uiutils/Header.vue'
import Footer from '../../uiutils/Footer.vue'
import UiIniciarSesion from '../uiiniciarsesion/UiIniciarSesion.vue'

defineProps<{
  email: Ref<string>
  password: Ref<string>
  handlerLogin: () => void
  handlerGoToCreateAccount: () => void
  handlerGoToRecoverPassword: () => void
}>()
</script>
