// react_ts/appjona_react_hooks/src/views/uihome/UiHome.tsx
// UiHome.tsx
// Visual template component — UI designer's responsibility
// Renders the layout with the login form injected via props
import React from 'react';
import { UiIniciarSesion } from '../uiiniciarsesion/UiIniciarSesion';
import BorderLayout from '../../uilayouts/BorderLayout';
import Header from '../../uiutils/Header';
import Footer from '../../uiutils/Footer';

interface UiHomeProps {
  email: string;
  password: string;
  setEmail: (v: string) => void;
  setPassword: (v: string) => void;
  handlerLogin: (e: React.FormEvent) => void;
  handlerGoToCreateAccount: () => void;
  handlerGoToRecoverPassword: () => void;
}

export const UiHome: React.FC<UiHomeProps> = (props) => {
  return (
    <BorderLayout
      north={<Header />}
      south={<Footer />}
      center={<UiIniciarSesion {...props} />}
    />
  );
};

// web_ts/appjona_vuejs/src/views/uihome/UiHome.vue
<!-- UiHome.vue -->
<!-- Capa: Template — layout visual de la vista Home -->
<!-- Restricciones: sin servicios externos, sin navegación, sin storage -->
<template>
  <BorderLayout>
    <template #north><Header /></template>
    <template #center>
      <UiIniciarSesion
        :email="email"
        :password="password"
        :handler-login="handlerLogin"
        :handler-go-to-create-account="handlerGoToCreateAccount"
        :handler-go-to-recover-password="handlerGoToRecoverPassword"
      />
    </template>
    <template #south><Footer /></template>
  </BorderLayout>
</template>

<script setup lang="ts">
import type { Ref } from 'vue'
import BorderLayout from '../../uilayouts/BorderLayout.vue'
import Header from '../../uiutils/Header.vue'
import Footer from '../../uiutils/Footer.vue'
import UiIniciarSesion from '../uiiniciarsesion/UiIniciarSesion.vue'

defineProps<{
  email: Ref<string>
  password: Ref<string>
  handlerLogin: () => void
  handlerGoToCreateAccount: () => void
  handlerGoToRecoverPassword: () => void
}>()
</script>
