// web_ts/appjona_vuejs/src/views/uihomesesion/UiHomeSessionView.vue
<!-- UiHomeSessionView.vue -->
<!-- Capa: View Orchestrator — instancia el Impl e inyecta en el Template -->
<!-- Registrado en el router en la ruta /homesesion -->
<template>
  <UiHomeSession v-bind="impl" />
</template>

<script setup lang="ts">
import { useUiHomeSessionImpl } from './use-ui-home-session-impl'
import UiHomeSession from './UiHomeSession.vue'

const impl = useUiHomeSessionImpl()
</script>

// web_ts/appjona_codex_react_hooks/src/views/uihomesesion/UiHomeSessionView.tsx
// Capa: View Orchestrator
// Responsabilidad: exponer la página autenticada como punto de entrada de ruta.
import { UiHomeSession } from './UiHomeSession';
import { useUiHomeSessionImpl } from './UiHomeSessionImpl';

export function UiHomeSessionView() {
  const impl = useUiHomeSessionImpl();
  return <UiHomeSession {...impl} />;
}
