// react_ts/appjona_react_hooks/src/views/uihomesesion/UiHomeSessionView.tsx
// UiHomeSessionView.tsx
// Orquesta: instancia el hook impl e inyecta en el componente visual
import React from 'react';
import { UiHomeSession } from './UiHomeSession';
import { useUiHomeSessionImpl } from './UiHomeSessionImpl';

export const UiHomeSessionView: React.FC = () => {
  const impl = useUiHomeSessionImpl();

  return <UiHomeSession {...impl} />;
};

// web_ts/appjona_vuejs/src/views/uihomesesion/UiHomeSessionView.vue
<!-- UiHomeSessionView.vue -->
<!-- Capa: View Orchestrator — instancia el Impl e inyecta en el Template -->
<!-- Registrado en el router en la ruta /homesesion -->
<template>
  <UiHomeSession v-bind="impl" />
</template>

<script setup lang="ts">
import { useUiHomeSessionImpl } from './use-ui-home-session-impl'
import UiHomeSession from './UiHomeSession.vue'

const impl = useUiHomeSessionImpl()
</script>
